matrix:
  - mpi_on
  - mpi_off

mpi_on:
  build:
    modules:
      - ecbuild
      - ninja
      - openmpi
    modules_package:
      - atlas:fftw,eigen
    dependencies:
      - ecmwf/eckit@develop
    parallel: 64
    ntasks: 16
    env:
      - ATLAS_FPE=0

mpi_off:
  build:
    modules:
      - ecbuild
      - ninja
    modules_package:
      - atlas:fftw,eigen
    dependencies:
      - ecmwf/eckit@develop
    parallel: 64
    env:
      - ATLAS_FPE=0
